### ISSUE TITLE
This is rad

### ISSUE THREAD

**Issue by skymoore** [cikent/Selenium-Projects#1]
Didn't know about selenium.  Glad you're writing code.  Hope all is well in your world dude.

**Comment by cikent** [comment]
Thanks for checking it out. You think that's cool,  you should check out: 
- https://github.com/cikent/Python-Web-UI-Test-Framework-Template; and
- https://github.com/cikent/Selenium-Projects/tree/master/Selenium-PythonProjects%2FFormy%20Python%20Test%20Framework

I'll update the Template project once I complete the improvements I'm working on in the Formy project. 

Hope you're well also, keep in touch!
